springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fitness_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
  flyway:
    enabled: false

app:
  swagger:
    public: true

groq:
  api:
    model: llama-3.1-8b-instant
