springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

spring:
  flyway:
    enabled: false

app:
  swagger:
    public: true

groq:
  api:
    model: llama-3.1-8b-instant
